name: test-ci

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential clang-tidy

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DENABLE_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run Tests
    # 低レイヤツールで管理者権限が必要な場合は sudo などを検討
      run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure